import { existsSync } from 'node:fs';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import ansiRegex from 'ansi-regex';
import { Command } from 'commander';
import { diff } from 'diff-match-patch-es';
import pc from 'picocolors';

import { ROOT_DIRECTORY, SANDBOX_DIRECTORY } from './utils/constants';
import { exec } from './utils/exec';

const PORT = process.env.STORYBOOK_SERVE_PORT
  ? Number.parseInt(process.env.STORYBOOK_SERVE_PORT, 10)
  : 6006;

const BUILDER_TO_SANDBOX: Record<string, string> = {
  'builder-vite': 'react-vite-default-ts',
  'builder-webpack5': 'react-webpack-18-ts',
};

const PROVISIONAL_HEADER = [
  '# PROVISIONAL BASELINE — requires reviewer approval before merge',
  '# Generated by: jiti scripts/capture-terminal-output.ts --builder <builder> --mode <mode> --update',
  '#',
  '# To update this baseline after reviewing, run:',
  '#   jiti scripts/capture-terminal-output.ts --builder <builder> --mode <mode> --update',
  '',
].join('\n');

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function normalizeOutput(raw: string, rootDir: string): string {
  const normalizedRoot = rootDir.replace(/\\/g, '/');
  const rootPattern = new RegExp(escapeRegExp(normalizedRoot), 'g');

  return (
    raw
      .replace(rootPattern, '<ROOT>')
      .replace(/\/(?:Users|home|tmp)\/[\w./-]+/g, '<ROOT>')
      .replace(/\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{3})?Z/g, '<TIMESTAMP>')
      .replace(/\b\d{2}:\d{2}:\d{2}\b/g, '<TIME>')
      .replace(/localhost:\d+/g, 'localhost:<PORT>')
      .replace(/\b(?:on\s+)?port\s+\d+\b/gi, 'port <PORT>')
      .replace(/\b(?:pid:\s*|PID\s+)\d+\b/g, 'pid: <PID>')
      .replace(
        /\b(?:built in\s*\d+(?:\.\d+)?\s*(?:ms|s)|done in\s*\d+(?:\.\d+)?\s*(?:ms|s)|in\s*\d+(?:\.\d+)?\s*ms)\b/gi,
        'built in <DURATION>'
      )
      // Normalize chunk hashes in bundle filenames (e.g., "8609.cbfa8718.iframe.bundle.js" -> "<CHUNK>.<HASH>.iframe.bundle.js")
      .replace(/\b(\d+)\.[a-f0-9]{8}\.iframe\.bundle\.js\b/g, '<CHUNK>.<HASH>.iframe.bundle.js')
      // Normalize hashes in static media files (e.g., "addon-library.7a58d2cb.png" -> "addon-library.<HASH>.png")
      .replace(/(static\/media\/[\w-]+)\.[a-f0-9]{8}\.(\w+)/g, '$1.<HASH>.$2')
      // Normalize any remaining hashes in main bundle files (e.g., "main.869457cc.iframe.bundle.js" -> "main.<HASH>.iframe.bundle.js")
      .replace(
        /\b(main|runtime~main)\.[a-f0-9]{8}\.iframe\.bundle\.js\b/g,
        '$1.<HASH>.iframe.bundle.js'
      )
      // Normalize file sizes (e.g., "(456 KiB)" or "(1.83 MiB)" -> "(<SIZE>)")
      .replace(/\(\d+(?:\.\d+)?\s*(?:KiB|MiB|GiB|KB|MB|GB|B)\)/g, '(<SIZE>)')
      // Normalize size limit values in warning messages (e.g., "244 KiB" -> "<SIZE>")
      .replace(/\b\d+(?:\.\d+)?\s*(?:KiB|MiB|GiB|KB|MB|GB|B)\b/g, '<SIZE>')
      .replace(/\bheap used:\s*\d+(?:\.\d+)?\s*(?:kB|KB|MB|GB)\b/gi, 'heap used: <MEMORY>')
      .replace(ansiRegex(), '')
      .replace(/\r\n/g, '\n')
      .trimEnd()
  );
}

function stripHeader(content: string): string {
  return content
    .replace(/^#.*$/gm, '')
    .replace(/^\s*\n/gm, '')
    .trimEnd();
}

function createUnifiedDiff(previous: string, next: string): string {
  const changes = diff(previous, next);
  const diffLines: string[] = ['--- baseline', '+++ current'];

  let beforeIndex = 1;
  let afterIndex = 1;
  let hunkStart = -1;
  const contextBuffer: Array<{ type: number; line: string }> = [];
  const CONTEXT_LINES = 3;

  for (const [changeType, text] of changes) {
    const lines = text.split('\n').filter((line) => line.length > 0);

    if (changeType === 0) {
      for (const line of lines) {
        contextBuffer.push({ type: 0, line });
        beforeIndex += 1;
        afterIndex += 1;
      }
    } else if (changeType === 1) {
      if (hunkStart === -1) {
        hunkStart = beforeIndex;
      }

      for (const line of lines) {
        contextBuffer.push({ type: 1, line });
        afterIndex += 1;
      }
    } else if (changeType === -1) {
      if (hunkStart === -1) {
        hunkStart = beforeIndex;
      }

      for (const line of lines) {
        contextBuffer.push({ type: -1, line });
        beforeIndex += 1;
      }
    }
  }

  if (contextBuffer.length === 0) {
    return diffLines.join('\n');
  }

  const hunkStart2 = Math.max(1, hunkStart - CONTEXT_LINES);
  const beforeCount = beforeIndex - hunkStart2;
  const afterCount = afterIndex - (hunkStart === -1 ? hunkStart2 : hunkStart2);

  diffLines.push(`@@ -${hunkStart2},${beforeCount} +${hunkStart2},${afterCount} @@`);

  for (const { type, line } of contextBuffer) {
    if (type === 0) {
      diffLines.push(` ${line}`);
    } else if (type === 1) {
      diffLines.push(`+${line}`);
    } else if (type === -1) {
      diffLines.push(`-${line}`);
    }
  }

  return diffLines.join('\n');
}

function buildCommand(mode: 'build' | 'dev'): string {
  if (mode === 'dev') {
    return `yarn storybook --ci --port ${PORT}`;
  }

  return 'yarn build-storybook --quiet';
}

async function main(): Promise<number> {
  const program = new Command();

  program
    .requiredOption('--builder <name>', 'builder target, e.g. builder-vite or builder-webpack5')
    .option('--mode <build|dev>', 'capture mode', 'build')
    .option('--update', 'overwrite snapshot and exit 0', false);

  program.parse(process.argv);

  const options = program.opts<{
    builder: string;
    mode: string;
    update: boolean;
  }>();

  if (options.mode !== 'build' && options.mode !== 'dev') {
    console.error(pc.red(`Invalid mode: ${options.mode}. Allowed values: build, dev`));
    return 1;
  }

  const sandboxKey = BUILDER_TO_SANDBOX[options.builder];

  if (!sandboxKey) {
    console.error(
      pc.red(
        `Unknown builder: ${options.builder}. Supported builders: ${Object.keys(BUILDER_TO_SANDBOX).join(', ')}`
      )
    );
    return 1;
  }

  const mode = options.mode as 'build' | 'dev';
  const command = buildCommand(mode);
  const sandboxDir = join(SANDBOX_DIRECTORY, sandboxKey);
  const currentDir = dirname(fileURLToPath(import.meta.url));
  const snapshotDir = join(currentDir, 'terminal-output-snapshots');
  const snapshotPath = join(snapshotDir, `${options.builder}-${mode}.snap.txt`);

  if (!existsSync(sandboxDir)) {
    console.error(pc.red(`Sandbox directory not found: ${sandboxDir}`));
    return 1;
  }

  const rawOutput = (await exec(command, { cwd: sandboxDir }, { debug: false }, true)) as string;
  const normalizedOutput = normalizeOutput(rawOutput, ROOT_DIRECTORY);

  await mkdir(snapshotDir, { recursive: true });

  if (options.update) {
    await writeFile(snapshotPath, `${normalizedOutput}\n`, 'utf8');
    console.log(pc.green(`Updated snapshot: ${snapshotPath}`));
    return 0;
  }

  if (!existsSync(snapshotPath)) {
    await writeFile(snapshotPath, `${PROVISIONAL_HEADER}${normalizedOutput}\n`, 'utf8');
    console.log(pc.yellow(`Created provisional baseline: ${snapshotPath}`));
    console.log(
      pc.yellow(
        '⚠️  PROVISIONAL BASELINE — requires reviewer approval before merge. Re-run with --update after review.'
      )
    );
    return 0;
  }

  const baseline = await readFile(snapshotPath, 'utf8');
  const strippedBaseline = stripHeader(baseline);

  if (strippedBaseline === normalizedOutput) {
    console.log(pc.green(`✅ Output matches baseline: ${snapshotPath}`));
    return 0;
  }

  const diffOutput = createUnifiedDiff(strippedBaseline, normalizedOutput);
  console.log(diffOutput);
  return 1;
}

main()
  .then((exitCode) => process.exit(exitCode))
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
